services:
  mysql:
    image: mysql:8.0
    environment:
      # 开发默认值请在 .env 或运行时覆盖，切勿用于生产
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-devOnly123!}
      MYSQL_DATABASE: ginkgoid
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "sh", "-lc", "mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD:-123465}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  server:
    build: .
    image: ginkgoid:latest
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment: {}
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro

