// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GinkgoID"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/openid-configuration": {
            "get": {
                "description": "返回 OpenID Provider 的发现文档（.well-known/openid-configuration）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "OIDC Discovery 文档",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/clients": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "description": "返回最多 1000 条客户端列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "列出客户端",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.ClientsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "description": "创建新的 OAuth 客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建客户端",
                "parameters": [
                    {
                        "description": "客户端信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UpsertClientReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/clients/table": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "description": "以 Layui 表格格式返回分页数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "客户端表格",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小(\u003c=200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.TableClientsResponse"
                        }
                    }
                }
            }
        },
        "/admin/api/clients/{id}": {
            "put": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新客户端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "client_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息（未提供的字段不变）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.UpsertClientReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/clients/{id}/status": {
            "patch": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "启停客户端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "client_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.ClientStatusPatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/consents": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "列出同意记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.ConsentsResponse"
                        }
                    }
                }
            }
        },
        "/admin/api/consents/table": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "description": "以 Layui 表格格式返回分页数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "同意记录表格",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小(\u003c=200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.TableConsentsResponse"
                        }
                    }
                }
            }
        },
        "/admin/api/consents/{id}": {
            "delete": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除同意记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "同意记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/jwks": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "列出 JWK",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/jwks/rotate": {
            "post": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "轮换 JWK",
                "parameters": [
                    {
                        "type": "string",
                        "description": "算法：ALL|RS256|ES256",
                        "name": "alg",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/ping": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "管理端 ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/tokens/revoke_access": {
            "post": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "撤销 Access Token",
                "parameters": [
                    {
                        "description": "Access Token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.RevokeAccessReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/tokens/revoke_jti": {
            "post": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "按 jti 撤销",
                "parameters": [
                    {
                        "description": "撤销参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.RevokeJTIReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/tokens/status": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "查询 jti 撤销状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT ID",
                        "name": "jti",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/users": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "列出用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.UsersResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.CreateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/users/table": {
            "get": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "description": "以 Layui 表格格式返回分页数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "用户表格",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小(\u003c=200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.TableUsersResponse"
                        }
                    }
                }
            }
        },
        "/admin/api/users/{id}/email": {
            "patch": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "设置用户邮箱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "邮箱信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.PatchUserEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/users/{id}/password": {
            "patch": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "重置用户口令",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "新密码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.PatchUserPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/users/{id}/role": {
            "patch": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "设置用户角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.PatchUserRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/api/users/{id}/sessions/revoke_all": {
            "post": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "撤销用户所有会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/authorize": {
            "get": {
                "description": "OIDC 授权端点（授权码 + PKCE），成功后 302 跳转携带 code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "授权端点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "仅支持 code",
                        "name": "response_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "回调地址（需预注册）",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "openID 相关 scopes，如: openid profile email",
                        "name": "scope",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF 防护/状态保持",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID Token nonce",
                        "name": "nonce",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PKCE 值",
                        "name": "code_challenge",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "S256",
                        "name": "code_challenge_method",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "重定向至 redirect_uri，附带 code/state",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/consent": {
            "get": {
                "description": "渲染授权同意页面",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "同意页",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "回调地址",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求的 scopes（空格分隔）",
                        "name": "scope",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态参数",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID Token nonce",
                        "name": "nonce",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PKCE code_challenge",
                        "name": "code_challenge",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PKCE 方法，S256",
                        "name": "code_challenge_method",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "用户在同意页提交表单后保存同意记录并签发授权码",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "同意提交",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "回调地址",
                        "name": "redirect_uri",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态参数",
                        "name": "state",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID Token nonce",
                        "name": "nonce",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "请求的 scopes（空格分隔）",
                        "name": "scope",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PKCE code_challenge",
                        "name": "code_challenge",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "S256",
                        "name": "code_challenge_method",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "记住授权：1 表示记住",
                        "name": "remember",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "会话 ID（兜底，从 Cookie 读取）",
                        "name": "sid",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "重定向至 redirect_uri，附带 code/state",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/debug/vars": {
            "get": {
                "description": "暴露 Go expvar 运行时变量（JSON）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "调试变量",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/docs": {
            "get": {
                "description": "渲染简单的服务说明页面",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "文档页",
                "responses": {
                    "200": {
                        "description": "HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "返回服务存活状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/jwks.json": {
            "get": {
                "description": "返回当前可用的 JWK 公钥列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "JWKS 公钥集",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "description": "渲染登录页面",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "登录页",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录成功后的跳转",
                        "name": "continue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "用户名/密码登录。成功后设置会话 Cookie；若提供 continue 参数则 302 跳转，否则返回 JSON。",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "表单登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录成功后的跳转地址",
                        "name": "continue",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "302": {
                        "description": "重定向至 continue",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "description": "清除 OP 会话并可按白名单回跳；兼容 OIDC RP 发起登出",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "注销会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RP 提供的 id_token",
                        "name": "id_token_hint",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "白名单内回调地址",
                        "name": "post_logout_redirect_uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态参数",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "以 Prometheus 文本格式暴露基础运行指标",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "基础指标",
                "responses": {
                    "200": {
                        "description": "prometheus text",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/oauth2/introspect": {
            "post": {
                "description": "RFC7662 自省端点，返回令牌是否有效等信息",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "令牌自省",
                "parameters": [
                    {
                        "type": "string",
                        "description": "待查询的令牌",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/oauth2/revoke": {
            "post": {
                "description": "RFC7009 撤销端点，支持 Access Token 撤销",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "令牌撤销",
                "parameters": [
                    {
                        "type": "string",
                        "description": "待撤销的令牌",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "返回 DB 与 Redis 的就绪状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "就绪检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/token": {
            "post": {
                "description": "使用授权码交换 Access Token 与 ID Token（需 PKCE）",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "令牌端点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "固定为 authorization_code",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "授权码",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "回调地址",
                        "name": "redirect_uri",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公有客户端在此携带",
                        "name": "client_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "机密客户端在此或 BasicAuth",
                        "name": "client_secret",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "PKCE 校验值",
                        "name": "code_verifier",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/userinfo": {
            "get": {
                "description": "使用 Bearer Access Token 获取用户信息（sub 必含，其它字段由 scope 决定）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ClientItem": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "post_logout_uris": {
                    "type": "string"
                },
                "redirect_uris": {
                    "type": "string"
                },
                "scopes": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "admin.ClientRow": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "客户端 ID\nexample: demo-web",
                    "type": "string"
                },
                "name": {
                    "description": "名称\nexample: Demo Web",
                    "type": "string"
                },
                "status": {
                    "description": "状态（1 启用 / 0 停用）\nexample: 1",
                    "type": "integer"
                }
            }
        },
        "admin.ClientStatusPatchReq": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "状态（1 启用 / 0 停用）\nexample: 1",
                    "type": "integer"
                }
            }
        },
        "admin.ClientsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.ClientItem"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "admin.ConsentRow": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "example: demo-web",
                    "type": "string"
                },
                "id": {
                    "description": "example: 9001",
                    "type": "integer"
                },
                "scopes": {
                    "description": "example: [\"openid\",\"profile\"]",
                    "type": "string"
                },
                "user_id": {
                    "description": "example: 1001",
                    "type": "integer"
                }
            }
        },
        "admin.ConsentsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.ConsentRow"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "admin.CreateUserReq": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱（可选）\nexample: alice@example.com",
                    "type": "string"
                },
                "email_verified": {
                    "description": "邮箱是否已验证（可选）\nexample: true",
                    "type": "boolean"
                },
                "password": {
                    "description": "密码\nexample: Secret123!",
                    "type": "string"
                },
                "role": {
                    "description": "角色（可选）\nexample: admin",
                    "type": "string"
                },
                "username": {
                    "description": "用户名\nexample: alice",
                    "type": "string"
                }
            }
        },
        "admin.PatchUserEmailReq": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱\nexample: alice@example.com",
                    "type": "string"
                },
                "email_verified": {
                    "description": "邮箱是否已验证（可选）\nexample: true",
                    "type": "boolean"
                }
            }
        },
        "admin.PatchUserPasswordReq": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "新密码\nexample: Secret123!",
                    "type": "string"
                }
            }
        },
        "admin.PatchUserRoleReq": {
            "type": "object",
            "properties": {
                "role": {
                    "description": "角色\nexample: operator",
                    "type": "string"
                }
            }
        },
        "admin.RevokeAccessReq": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "Access Token\nexample: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...",
                    "type": "string"
                }
            }
        },
        "admin.RevokeJTIReq": {
            "type": "object",
            "properties": {
                "jti": {
                    "description": "JWT ID\nexample: 3c2e1f8a-9a50-4d9c-9b59-2b3f0baf7a2f",
                    "type": "string"
                },
                "ttl_seconds": {
                    "description": "过期时间（秒）\nexample: 600",
                    "type": "integer"
                }
            }
        },
        "admin.TableClientsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务码：0 表示成功\nexample: 0",
                    "type": "integer"
                },
                "count": {
                    "description": "记录总数\nexample: 42",
                    "type": "integer"
                },
                "data": {
                    "description": "数据行",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.ClientRow"
                    }
                },
                "msg": {
                    "description": "消息\nexample: ok",
                    "type": "string"
                },
                "request_id": {
                    "description": "请求 ID\nexample: 9P8sJ0n2qWfD",
                    "type": "string"
                }
            }
        },
        "admin.TableConsentsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.ConsentRow"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "admin.TableUsersResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.UserRow"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "admin.UpsertClientReq": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "post_logout_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "secret": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "admin.UserRow": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "example: alice@example.com",
                    "type": "string"
                },
                "email_verified": {
                    "description": "example: true",
                    "type": "boolean"
                },
                "id": {
                    "description": "example: 1001",
                    "type": "integer"
                },
                "role": {
                    "description": "example: admin",
                    "type": "string"
                },
                "status": {
                    "description": "example: 1",
                    "type": "integer"
                },
                "username": {
                    "description": "example: alice",
                    "type": "string"
                }
            }
        },
        "admin.UsersResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin.UserRow"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "CSRF": {
            "type": "apiKey",
            "name": "X-CSRF-Token",
            "in": "header"
        },
        "Session": {
            "type": "apiKey",
            "name": "sid",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "GinkgoID OpenAPI",
	Description:      "GinkgoID 提供的公开 OIDC 端点与管理后台 API。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
