// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GinkgoID Team",
            "url": "https://xray.top",
            "email": "lushi78778@xray.top"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/oauth-authorization-server": {
            "get": {
                "description": "获取 OpenID Provider 的元数据文档",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "OIDC Discovery",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/oidc.Discovery"
                        }
                    }
                }
            }
        },
        "/.well-known/openid-configuration": {
            "get": {
                "description": "获取 OpenID Provider 的元数据文档",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "OIDC Discovery",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/oidc.Discovery"
                        }
                    }
                }
            }
        },
        "/api/consents": {
            "get": {
                "description": "列出当前用户对各客户端已授予的 scope",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consent-api"
                ],
                "summary": "授权记录列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/consents/{client_id}": {
            "delete": {
                "description": "撤销当前用户对指定 client 的授权，并尝试吊销关联的刷新令牌",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consent-api"
                ],
                "summary": "撤销授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "description": "读取当前登录用户的基础资料",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-api"
                ],
                "summary": "当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "更新当前登录用户的姓名/邮箱",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-api"
                ],
                "summary": "更新我的资料",
                "parameters": [
                    {
                        "description": "{name,email}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/me/password": {
            "post": {
                "description": "需要提供旧口令与新口令",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-api"
                ],
                "summary": "修改我的口令",
                "parameters": [
                    {
                        "description": "{oldPassword,newPassword}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/my/clients": {
            "get": {
                "description": "返回我拥有的已注册客户端（应用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-api"
                ],
                "summary": "我的应用列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/my/clients/{client_id}": {
            "delete": {
                "description": "物理删除我拥有的客户端",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-api"
                ],
                "summary": "删除我的客户端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/my/clients/{client_id}/disable": {
            "put": {
                "description": "将指定客户端置为未批准（approved=false）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-api"
                ],
                "summary": "禁用我的客户端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-api"
                ],
                "summary": "管理员 - 用户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-api"
                ],
                "summary": "管理员 - 创建用户",
                "parameters": [
                    {
                        "description": "{username,password,email,name,is_admin,is_dev}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-api"
                ],
                "summary": "管理员 - 更新用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{email,name,is_admin,is_dev,password}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/authorize": {
            "get": {
                "description": "实现授权码 + PKCE 及可选 Hybrid 流程",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "oauth2"
                ],
                "summary": "授权端点（Authorization）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code 或 code id_token",
                        "name": "response_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "重定向 URI",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "openid 等空格分隔",
                        "name": "scope",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态参数",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Hybrid 必需",
                        "name": "nonce",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "fragment|form_post|query",
                        "name": "response_mode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PKCE 挑战",
                        "name": "code_challenge",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "S256|plain",
                        "name": "code_challenge_method",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "none|login|consent",
                        "name": "prompt",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ACR 要求",
                        "name": "acr_values",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "重定向到 redirect_uri",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/check_session": {
            "get": {
                "description": "用于 RP 轮询检查 OP 登录状态的 iframe",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "session-management"
                ],
                "summary": "会话探测 Iframe（简化）",
                "responses": {
                    "200": {
                        "description": "HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/consent": {
            "get": {
                "description": "显示授权范围供用户确认",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ui"
                ],
                "summary": "授权同意页",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求的 scope（空格分隔）",
                        "name": "scope",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "处理用户对授权的同意或拒绝",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ui"
                ],
                "summary": "提交授权同意",
                "parameters": [
                    {
                        "type": "string",
                        "description": "approve 或 deny",
                        "name": "decision",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "重定向至 /authorize",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dev/keys/rotate": {
            "post": {
                "description": "（仅限非生产环境）触发一次新的 JWK 生成",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "开发辅助 - 轮换密钥",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dev/users": {
            "get": {
                "description": "（仅限非生产环境）列出所有用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "开发辅助 - 用户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "（仅限非生产环境）快速创建用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "开发辅助 - 创建用户",
                "parameters": [
                    {
                        "description": "{username,password}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/introspect": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "返回访问令牌的有效性与基础元信息",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth2"
                ],
                "summary": "内省端点（Introspection）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要内省的令牌",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ active: bool, ... }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/jwks.json": {
            "get": {
                "description": "返回用于验证 ID Token/Access Token 的公钥集合（JWK Set）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "JWKS 公钥集合",
                "responses": {
                    "200": {
                        "description": "JWKS JSON",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "description": "显示用户名密码登录表单",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ui"
                ],
                "summary": "登录页",
                "responses": {
                    "200": {
                        "description": "HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "处理用户名密码登录请求",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ui"
                ],
                "summary": "提交登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "重定向至 /authorize",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "HTML 登录页（含错误）",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "description": "清理 OP 会话并通知已登录 RP；可选重定向",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "session-management"
                ],
                "summary": "注销（RP-Initiated Logout）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RP 提供的 ID Token",
                        "name": "id_token_hint",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "注销后重定向 URI",
                        "name": "post_logout_redirect_uri",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "重定向回传状态",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML 或 302 重定向",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "暴露 Prometheus 指标（text/plain; version=0.0.4）",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Prometheus 指标",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "get": {
                "description": "使用 registration_access_token 返回客户端元数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "获取已注册客户端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer {registration_access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "使用 registration_access_token 更新客户端元数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "更新已注册客户端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer {registration_access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "变更字段",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "按 OIDC Dynamic Client Registration 注册新客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "动态注册客户端",
                "parameters": [
                    {
                        "description": "注册请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/services.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "使用 registration_access_token 将客户端标记为未批准",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "禁用已注册客户端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer {registration_access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/register/rotate": {
            "post": {
                "description": "使用现有 registration_access_token 轮换获取新的 token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registration"
                ],
                "summary": "轮换 Registration Access Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户端 ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer {registration_access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"registration_access_token\\\":\\\"...\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/revoke": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "撤销访问令牌或刷新令牌",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth2"
                ],
                "summary": "吊销端点（Revocation）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要撤销的令牌",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "access_token|refresh_token",
                        "name": "token_type_hint",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/token": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "交换授权码为令牌，或使用刷新令牌换新令牌",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth2"
                ],
                "summary": "令牌端点（Token）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization_code 或 refresh_token",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "授权码（授权码模式）",
                        "name": "code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "必须与授权时相同",
                        "name": "redirect_uri",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "PKCE 校验所需",
                        "name": "code_verifier",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "刷新令牌（刷新模式）",
                        "name": "refresh_token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "当未使用 Basic 时必填",
                        "name": "client_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "当未使用 Basic 时必填",
                        "name": "client_secret",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "包含 access_token/id_token/refresh_token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/userinfo": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使用 Access Token 获取用户 claims 信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oidc"
                ],
                "summary": "用户信息端点（UserInfo）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "当未设置 Authorization 时可使用",
                        "name": "access_token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使用 Access Token 获取用户 claims 信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oidc"
                ],
                "summary": "用户信息端点（UserInfo）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "当未设置 Authorization 时可使用",
                        "name": "access_token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "oidc.Discovery": {
            "type": "object",
            "properties": {
                "acr_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorization_endpoint": {
                    "type": "string"
                },
                "backchannel_logout_session_supported": {
                    "type": "boolean"
                },
                "backchannel_logout_supported": {
                    "type": "boolean"
                },
                "check_session_iframe": {
                    "type": "string"
                },
                "claims_parameter_supported": {
                    "type": "boolean"
                },
                "claims_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code_challenge_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_session_endpoint": {
                    "type": "string"
                },
                "frontchannel_logout_session_supported": {
                    "type": "boolean"
                },
                "frontchannel_logout_supported": {
                    "type": "boolean"
                },
                "grant_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id_token_signing_alg_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "introspection_endpoint": {
                    "type": "string"
                },
                "issuer": {
                    "type": "string"
                },
                "jwks_uri": {
                    "type": "string"
                },
                "prompt_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "registration_endpoint": {
                    "type": "string"
                },
                "request_parameter_supported": {
                    "type": "boolean"
                },
                "request_uri_parameter_supported": {
                    "type": "boolean"
                },
                "response_modes_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "response_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "revocation_endpoint": {
                    "type": "string"
                },
                "scopes_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subject_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_endpoint": {
                    "type": "string"
                },
                "token_endpoint_auth_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userinfo_endpoint": {
                    "type": "string"
                }
            }
        },
        "services.RegisterRequest": {
            "type": "object",
            "properties": {
                "application_type": {
                    "type": "string"
                },
                "backchannel_logout_uri": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "frontchannel_logout_uri": {
                    "type": "string"
                },
                "grant_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "logo_uri": {
                    "type": "string"
                },
                "post_logout_redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "response_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scope": {
                    "type": "string"
                },
                "sector_identifier_uri": {
                    "type": "string"
                },
                "subject_type": {
                    "description": "取值：public 或 pairwise",
                    "type": "string"
                },
                "token_endpoint_auth_method": {
                    "type": "string"
                }
            }
        },
        "services.RegisterResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_id_issued_at": {
                    "type": "integer"
                },
                "client_secret": {
                    "type": "string"
                },
                "client_secret_expires_at": {
                    "type": "integer"
                },
                "grant_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "registration_access_token": {
                    "type": "string"
                },
                "registration_client_uri": {
                    "type": "string"
                },
                "token_endpoint_auth_method": {
                    "type": "string"
                }
            }
        },
        "storage.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "emailVerified": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "isDev": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "description": "已哈希的口令",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "GinkgoID OIDC OP API",
	Description:      "基于 Go(Gin) 的 OpenID Provider，实现 Discovery、JWKS、授权码+PKCE、Token、UserInfo、动态注册、注销、撤销、内省等接口。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
